import { SidebarComp } from "@/Components/SidebarComp/SidebarComp";
import type { Metadata } from "next";
// import Sidebar from "./@sidebar/default";




export const metadata: Metadata = {
  title: "Learning Management System",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children
}: Readonly<{
  children: React.ReactNode;
  
  

}>) {
  return (
    
        <section className="w-screen h-screen xl:max-h-[1400px] xl:flex">
         <SidebarComp/>
        <div className="w-full h-full xl:w-[50%] ">
           {children}
        </div>
        </section>

  );
}
