import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GeneralLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 <>
        <section className="w-screen max-h-[1500px] h-[900px] flex flex-col special:h-1400px md:h-[1200px] xl:flex xl:flex-row xl:h-screen xl:justify-around">
        {children}
        </section>
 </>
 
    
      
  );
}
